version: '3'

services:
  jira1:
    image: atlassian/jira-software:latest
    container_name: jira1
    environment:
      - JIRA_NODE_ID=1
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/sharedhome
      - JIRA_HOME=/var/atlassian/application-data/jira1
      - ATL_JDBC_URL=jdbc:postgresql://db/jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - CLUSTERED=true
      - JIRA_NODE_ID=node_1
      - ATL_PROXY_NAME=<local-ip-address>
      - ATL_PROXY_PORT=80
    networks:
      - jiranet
    depends_on:
      - db
    volumes:
      - jira-shared-home:/var/atlassian/application-data/jira/sharedhome
      - jira1-home:/var/atlassian/application-data/jira1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.rule=Host(`<local-ip-address>`)"
      - "traefik.http.routers.jira.entrypoints=web"
      - "traefik.http.services.jira.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.jira.loadBalancer.sticky.cookie.name=jira_cookie"
      - "traefik.http.services.jira.loadbalancer.server.port=8080"

  jira2:
    image: atlassian/jira-software:latest
    container_name: jira2
    environment:
      - JIRA_NODE_ID=2
      - JIRA_SHARED_HOME=/var/atlassian/application-data/jira/sharedhome
      - JIRA_HOME=/var/atlassian/application-data/jira2
      - ATL_JDBC_URL=jdbc:postgresql://db/jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - CLUSTERED=true
      - JIRA_NODE_ID=node_2
      - ATL_PROXY_NAME=<local-ip-address>
      - ATL_PROXY_PORT=80
    networks:
      - jiranet
    depends_on:
      - db
    volumes:
      - jira-shared-home:/var/atlassian/application-data/jira/sharedhome
      - jira2-home:/var/atlassian/application-data/jira2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.rule=Host(`<local-ip-address>`)"
      - "traefik.http.routers.jira.entrypoints=web"
      - "traefik.http.services.jira.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.jira.loadBalancer.sticky.cookie.name=jira_cookie"
      - "traefik.http.services.jira.loadbalancer.server.port=8080"

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jiranet
    ports:
      - 1234:5432

  traefik:
    image: traefik:v2.5
    container_name: traefiklb
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 1010:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jiranet

networks:
  jiranet:
    driver: bridge

volumes:
  postgres-data:
  jira-shared-home:
  jira1-home:
  jira2-home:

